# base config file

# script config groups
defaults:
- sampling: celeba_5
- blackbox_sample_query: inception_resnetv1_vggface2
- surrogate_training: inception_resnetv1_casia
- attack_execution: SMILE_default
- _self_

device: "cuda"
seed: 666

# output dir
hydra:
  run:
    dir: output/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# override specific values 
# sampling:
#   output_dir: "new_samples"
#   size: 100