# base config file

# script config groups
defaults:
- sampling: celeba_5
- blackbox_sample_query: resnet50_vggface2
- surrogate_training:

device: "cuda"



# override specific values

# sampling:
#   output_dir: "new_samples"
#   size: 100