# base config file

# script config groups
defaults:
- sampling: celeba_5
- blackbox_sample_query: inception_resnetv1_vggface2
- surrogate_training: inception_resnetv1_casia
- attack_execution: SMILE_default

device: "cuda"
seed: 666



# override specific values

# sampling:
#   output_dir: "new_samples"
#   size: 100